### ISSUE TITLE
Facebook Engineer wanted!

### ISSUE THREAD

**Issue by kzima** [Brisbane-React-JS/meetups#31]
I got a contact with one of the engineers from Facebook that is looking for a vanilla JavaScript  developer. You would be required to build stuff from scratch, know the difference between call and apply and have a good knowledge of a DOM tree and its inner workings.

Position is available in either Washington or London. If you are interested, please send me a message!

**Comment by jwulf** [comment]
They are not looking for a vanilla JS dev, they are testing devs on vanilla JS because they are looking for people who understand the fundamentals of the language enough to write new frameworks and languages. 

They'll contact you if your GitHub mojo is strong enough. No need to do anything apart from commit every day and be awesome.
